<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4qcLica\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4qcLica/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4qcLica.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4qcLica\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container4qcLica\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '4qcLica',
    'container.build_id' => '0662f3ba',
    'container.build_time' => 1771161242,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4qcLica');
